# Generated by Django 5.1 on 2024-09-24 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('cake', '0002_remove_account_cards_saved_remove_review_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('rating', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='account.account')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake_reviews', to='cake.cake')),
            ],
        ),
    ]
