# Generated by Django 5.1 on 2024-09-24 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cards_saved',
        ),
        migrations.RemoveField(
            model_name='review',
            name='account',
        ),
        migrations.RemoveField(
            model_name='card',
            name='account',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='account.account'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='review',
            name='cake',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
