# Generated by Django 5.1 on 2024-11-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_alter_cake_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='toppings',
            field=models.CharField(choices=[('sprinkles', 'Sprinkles'), ('chocolate_chips', 'Chocolate Chips'), ('fruits', 'Fruits'), ('nuts', 'Nuts'), ('whipped_cream', 'Whipped Cream')], default='sprinkles', max_length=30),
        ),
    ]
