# Generated by Django 5.1 on 2024-09-24 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=16)),
                ('arrival_date', models.DateField()),
                ('delivery_status', models.CharField(max_length=32)),
                ('delivery_price', models.IntegerField(default=10000)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.account')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.cart')),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.delivery')),
            ],
        ),
    ]
